### ISSUE TITLE
Support for V1.0 purple SATA interface board

### ISSUE THREAD

**Issue by burgsth** [jeffqchen/PS2EasyHDD#1]
I have a V1.0 purple SATA interface board with a slightly different component layout.
It won't fit into the printed part.

If needed I can add more dimension informations.
![IMG_3753](https://github.com/jeffqchen/PS2EasyHDD/assets/125667885/f22cc723-2d6d-48e7-add6-0de9bc8c091b)

**Comment by jeffqchen** [comment]
I don't have the v1.0 board on hand, but I have found pictures online. This will not be accurate and could lead to issues. And it will take a bit of time to add to the models.

If you can't wait, consider getting a v2.0 for now.

**Comment by jeffqchen** [comment]
I have added amends to the model to account for the extra components on the v1.0 board. Please check the updated files.

**Comment by burgsth** [comment]
The FFC connector seems to be slightly larger than on v2.0 boards, they do not fit into the gap. Lack of about 0.5mm on each side.
Will dremel the FCC gap tomorrow, now I'm printing the inner tray and will test tomorrow.

**Comment by jeffqchen** [comment]
Please download the latest Sata Board Cover.stl. I widened it by 1mm on each side.

**Comment by burgsth** [comment]
The SATA board cover seems to be fine now. The component skip on the inner tray needs to be moved about 2mm to the right (away from power connector skip) to fit the component.

**Comment by jeffqchen** [comment]
Fixed the Inner Tray. Please check again.

**Comment by burgsth** [comment]
Everything fits perfect, thank you very much.
Now I'll print the mainboard parts.

**Comment by jeffqchen** [comment]
Thank you very much for your help!
