### ISSUE TITLE
Missing hole on other revision of Mainboard

### ISSUE THREAD

**Issue by burgsth** [jeffqchen/PS2EasyHDD#2]
I have a SCPH-10350 with a BA-005 Mainboard which lacks of the mounting hole of your uses BA-006.
![IMG_3754](https://github.com/jeffqchen/PS2EasyHDD/assets/125667885/323bab3a-7afd-4eda-b9af-747fe25e5c36)

The PCB seems to fit nearly into the case, so only a other position of the hole would be needed.
Only right side is slightly different.

**Comment by jeffqchen** [comment]
I'll add that in soon. With the two existing holes, it should be sturdy enough to use for the time being.

**Comment by jeffqchen** [comment]
I have moved the M3 screw position to use the hole you indicated. Please check the new files.

**Comment by burgsth** [comment]
The right hole needs to be slightly larger
![IMG_3768](https://github.com/jeffqchen/PS2EasyHDD/assets/125667885/96cfe638-8566-4a31-b93e-a56fb1b2cc2b)

**Comment by jeffqchen** [comment]
The two holes are of the same size. However since it's on a precarious location, it might end up being printed crooked. You can widen it by shoving the M3 hex screw driver bit into it and twist a few times.

**Comment by burgsth** [comment]
Sorry, I ment the VS32AH hole. I've marked the part red.

![IMG_3768 (1)](https://github.com/jeffqchen/PS2EasyHDD/assets/125667885/777dbaa3-b351-469d-9662-efd3319422ae)

On the other part, there are some condensators which need a change in the cover to fit. (marked black)

![IMG_3778](https://github.com/jeffqchen/PS2EasyHDD/assets/125667885/1d9c2ca5-4ba0-4815-b02e-ecd803d072cf)

**Comment by jeffqchen** [comment]
Did fixes according to your info. Please check the updated pieces.

**Comment by jeffqchen** [comment]
Thanks. I've removed that stub. It only exists on the newer rev.

**Comment by burgsth** [comment]
Assembles fine now without flaws, thank you very very much for your help!
Only thing maybe is to make the holes for screw heads slightly larger, I need to get screws with smaller heads.

I have some more slim and fat adapters. If you are interessted I can take a look at the mainboard revision and testprint your designs to verify.

**Comment by jeffqchen** [comment]
Thank you for your help. I'm still working on the 10281 for now and it will be available as soon as it's verified by me personally. Hopefully all the fixes you suggested were already put in it. Thank you for all your help!
