### ISSUE TITLE
Incorrect number of cables

### ISSUE THREAD

**Issue by hadess** [jeffqchen/PS2EasyHDD#6]
Very important ;)

We just need 4 of the 5 cables in the JST plug if we make it ourselves, so:
```diff
+ [5x] Pre-crimped JST cable. 15cm long. 
- [4x] Pre-crimped JST cable. 15cm long. 
```

I've verified that this applies to the Gamestar variant, not sure about the others.

**Comment by jeffqchen** [comment]
It's not incorrect. We are not gonna cheap out on a ground connection that GameStar decided to do just to save a few cents. We are not gonna sink down to their level.

**Comment by hadess** [comment]
> It's not incorrect. We are not gonna cheap out on a ground connection that GameStar decided to do just to save a few cents. We are not gonna sink down to their level.

OK, I looked at the 3 install pages, and all three showed a 5-pin cable with 4 actual wires, hence why I filed this issue in the first place. I guess I'll install that last wire then ;)
