### ISSUE TITLE
Gamestar STL - Inner Tray Long.stl - Wrong version (Does not fit)

### ISSUE THREAD

**Issue by stefanpausch** [jeffqchen/PS2EasyHDD#7]
I printed the Gamestar Inner Tray Long.stl multiple times and tried to insert different gamestar PCBs with the "Inner Shell.stl" attached. It does not fit.

The "Inner Tray Short.stl" fits and no issue with that.

I compored the Short and Long version and it seems that the front slope on the short version is deeper and fixes the issue the long version has.

I hope it is understandable what i mean :) - If not let me know and i will attach photos/screenshots.

Thanks a lot!

**Comment by jeffqchen** [comment]
Thank you. You are right. That was an oversight. I've fixed the problem with the long one.
