### ISSUE TITLE
Gamestar - Inner Shell - Issue in model on port

### ISSUE THREAD

**Issue by stefanpausch** [jeffqchen/PS2EasyHDD#8]
The parts near the port connector print disconnected in the Inner Shell on the Gamestar model.

I printed this part a few weeks ago (with an older file) and there was no issue.

I tested different slicers and printers

Problem appears on 0.2 and higher. Print looks fine on 0.15 and lower 

Example in prusaslicer : 

![prusa-slicer_TcYphOYD62](https://github.com/jeffqchen/PS2EasyHDD/assets/184467/45362739-c09a-4127-a9f0-7f78513be872)

**Comment by jeffqchen** [comment]
This part is non-essential. It doesn't matter if it came out nasty, as long as the opening is not blocked.
